import type { BankList } from "./types"

export const BANK_DATA: BankList = {
    banks: [
        { value: "bank_harda", label: "ALLO BANK/BANK HARDA INTERNASIONAL" },
        { value: "bank_anz", label: "ANZ INDONESIA" },
        { value: "bank_atmb_lsb", label: "ATMB LSB (BPR LSB)" },
        { value: "bank_atmb_plus", label: "ATMB PLUS" },
        { value: "bank_aceh", label: "BANK ACEH SYARIAH" },
        { value: "bank_aladin", label: "BANK ALADIN SYARIAH" },
        { value: "bank_amar", label: "BANK AMAR INDONESIA" },
        { value: "bank_antardaerah", label: "BANK ANTARDAERAH" },
        { value: "bank_artha", label: "BANK ARTHA GRAHA INTERNASIONAL" },
        { value: "bank_bengkulu", label: "BANK BENGKULU" },
        { value: "bank_btpn_syr", label: "BANK BTPN SYARIAH" },
        { value: "bank_bukopin_syr", label: "BANK BUKOPIN SYARIAH" },
        { value: "bank_bumi_arta", label: "BANK BUMI ARTA" },
        { value: "bank_capital", label: "BANK CAPITAL INDONESIA" },
        { value: "bank_ccb", label: "BANK CHINA CONSTRUCTION BANK INDONESIA" },
        { value: "bank_cnb", label: "BANK CNB (CENTRATAMA NASIONAL BANK)" },
        { value: "bank_danamon_syr", label: "BANK DANAMON SYARIAH" },
        { value: "bank_dinar", label: "BANK DINAR INDONESIA" },
        { value: "bank_dki", label: "BANK DKI JAKARTA" },
        { value: "bank_dki_syr", label: "BANK DKI SYARIAH" },
        { value: "bank_ganesha", label: "BANK GANESHA" },
        { value: "bank_agris", label: "BANK IBK INDONESIA" },
        { value: "bank_ina_perdana", label: "BANK INA PERDANA" },
        { value: "bank_index_selindo", label: "BANK INDEX SELINDO" },
        { value: "bank_artos_syr", label: "BANK JAGO SYARIAH" },
        { value: "bank_jambi", label: "BANK JAMBI" },
        { value: "bank_jambi_syr", label: "BANK JAMBI SYARIAH" },
        { value: "bank_jasa_jakarta", label: "BANK JASA JAKARTA" },
        { value: "bank_jawa_tengah", label: "BANK JATENG" },
        { value: "bank_jawa_tengah_syr", label: "BANK JATENG SYARIAH" },
        { value: "bank_jawa_timur", label: "BANK JATIM" },
        { value: "bank_jawa_timur_syr", label: "BANK JATIM SYARIAH" },
        { value: "bank_kalimantan_barat", label: "BANK KALBAR" },
        { value: "bank_kalimantan_barat_syr", label: "BANK KALBAR SYARIAH" },
        { value: "bank_kalimantan_selatan", label: "BANK KALSEL" },
        { value: "bank_kalimantan_selatan_syr", label: "BANK KALSEL SYARIAH" },
        { value: "bank_kalimantan_tengah", label: "BANK KALTENG" },
        { value: "bank_kalimantan_timur", label: "BANK KALTIMTARA" },
        { value: "bank_kalimantan_timur_syr", label: "BANK KALTIMTARA SYARIAH" },
        { value: "bank_lampung", label: "BANK LAMPUNG" },
        { value: "bank_maluku", label: "BANK MALUKU" },
        { value: "bank_mantap", label: "BANK MANTAP (MANDIRI TASPEN)" },
        { value: "bank_maspion", label: "BANK MASPION INDONESIA" },
        { value: "bank_mayapada", label: "BANK MAYAPADA" },
        { value: "bank_mayora", label: "BANK MAYORA INDONESIA" },
        { value: "bank_mega", label: "BANK MEGA" },
        { value: "bank_mega_syr", label: "BANK MEGA SYARIAH" },
        { value: "bank_mestika_dharma", label: "BANK MESTIKA DHARMA" },
        { value: "bank_mizuho", label: "BANK MIZUHO INDONESIA" },
        { value: "bank_mas", label: "BANK MULTI ARTA SENTOSA (BANK MAS)" },
        { value: "bank_mutiara", label: "BANK MUTIARA" },
        { value: "bank_sumatera_barat_syr", label: "BANK NAGARI SYARIAH" },
        { value: "bank_nusa_tenggara_barat", label: "BANK NTB SYARIAH" },
        { value: "bank_nusa_tenggara_timur", label: "BANK NTT" },
        { value: "bank_nusantara_parahyangan", label: "BANK NUSANTARA PARAHYANGAN" },
        { value: "bank_america_na", label: "BANK OF AMERICA NA" },
        { value: "bank_boc", label: "BANK OF CHINA (HONG KONG) LIMITED" },
        { value: "bank_india", label: "BANK OF INDIA INDONESIA" },
        { value: "bank_tokyo", label: "BANK OF TOKYO MITSUBISHI UFJ" },
        { value: "bank_papua", label: "BANK PAPUA" },
        { value: "bank_permata", label: "BANK PERMATA" },
        { value: "bank_prima", label: "BANK PRIMA MASTER" },
        { value: "bank_resona_perdania", label: "BANK RESONA PERDANIA" },
        { value: "bank_riau_dan_kepri", label: "BANK RIAU KEPRI" },
        { value: "bank_sahabat_sampoerna", label: "BANK SAHABAT SAMPOERNA" },
        { value: "bank_shinhan", label: "BANK SHINHAN INDONESIA" },
        { value: "bank_sinarmas", label: "BANK SINARMAS" },
        { value: "bank_sinarmas_syr", label: "BANK SINARMAS SYARIAH" },
        { value: "bank_sulselbar", label: "BANK SULSELBAR" },
        { value: "bank_sulselbar_syr", label: "BANK SULSELBAR SYARIAH" },
        { value: "bank_sulawesi", label: "BANK SULTENG" },
        { value: "bank_sulawesi_tenggara", label: "BANK SULTRA" },
        { value: "bank_sulut", label: "BANK SULUTGO" },
        { value: "bank_sumatera_barat", label: "BANK SUMBAR (BANK NAGARI)" },
        { value: "bank_sumsel_dan_babel", label: "BANK SUMSEL BABEL" },
        { value: "bank_sumsel_dan_babel_syr", label: "BANK SUMSEL BABEL SYARIAH" },
        { value: "bank_sumut", label: "BANK SUMUT" },
        { value: "bank_sumut_syr", label: "BANK SUMUT SYARIAH" },
        { value: "bank_victoria_internasional", label: "BANK VICTORIA INTERNATIONAL" },
        { value: "bank_victoria_syr", label: "BANK VICTORIA SYARIAH" },
        { value: "bank_woori", label: "BANK WOORI SAUDARA" },
        { value: "bank_bca", label: "BCA" },
        { value: "bank_bca_syr", label: "BCA (BANK CENTRAL ASIA) SYARIAH" },
        { value: "bank_billfazz", label: "BILLFAZZ" },
        { value: "bank_bjb", label: "BJB" },
        { value: "bank_bjb_syr", label: "BJB SYARIAH" },
        { value: "bank_royal", label: "BLU/BCA DIGITAL" },
        { value: "bank_bni", label: "BNI" },
        { value: "bank_bnp_paribas", label: "BNP PARIBAS INDONESIA" },
        { value: "bank_bali", label: "BPD BALI" },
        { value: "bank_banten", label: "BPD BANTEN" },
        { value: "bank_daerah_istimewa", label: "BPD DIY" },
        { value: "bank_daerah_istimewa_syr", label: "BPD DIY SYARIAH" },
        { value: "bank_eka", label: "BPR EKA (BANK EKA)" },
        { value: "bank_bri", label: "BRI" },
        { value: "bank_agroniaga", label: "BRI AGRONIAGA" },
        { value: "bank_bsm", label: "BSI (BANK SYARIAH INDONESIA)" },
        { value: "bank_btn", label: "BTN" },
        { value: "bank_btn_syr", label: "BTN SYARIAH" },
        { value: "bank_tabungan_pensiunan_nasional", label: "BTPN / JENIUS / BTPN WOW!" },
        { value: "bank_cimb", label: "CIMB NIAGA/CIMB NIAGA SYARIAH" },
        { value: "bank_citibank", label: "CITIBANK" },
        { value: "bank_commonwealth", label: "COMMONWEALTH BANK" },
        { value: "bank_chinatrust", label: "CTBC (CHINATRUST) INDONESIA" },
        { value: "bank_danamon", label: "DANAMON / DANAMON SYARIAH" },
        { value: "bank_dbs", label: "DBS INDONESIA" },
        { value: "bank_dompetku", label: "DOMPETKU" },
        { value: "bank_dutamoney", label: "DUTAMONEY" },
        { value: "bank_e2pay", label: "E2PAY" },
        { value: "bank_finnet", label: "FINNET" },
        { value: "bank_hsbc", label: "HSBC INDONESIA" },
        { value: "bank_icbc", label: "ICBC INDONESIA" },
        { value: "bank_artos", label: "JAGO/ARTOS" },
        { value: "bank_jpmorgan_chase", label: "KC JPMORGAN CHASE BANK" },
        { value: "bank_hana", label: "LINE BANK/KEB HANA" },
        { value: "bank_mandiri", label: "MANDIRI" },
        { value: "bank_bii", label: "MAYBANK INDONESIA" },
        { value: "bank_bii_syr", label: "MAYBANK INDONESIA SYARIAH" },
        { value: "bank_midtrans", label: "MIDTRANS" },
        { value: "bank_mnc_internasional", label: "MOTION/MNC BANK" },
        { value: "bank_muamalat", label: "MUAMALAT" },
        { value: "bank_yudha_bakti", label: "NEO COMMERCE/YUDHA BHAKTI" },
        { value: "bank_nationalnobu", label: "NOBU (NATIONALNOBU) BANK" },
        { value: "bank_ocbc", label: "OCBC NISP" },
        { value: "bank_ocbc_syr", label: "OCBC NISP SYARIAH" },
        { value: "bank_panin", label: "PANIN BANK" },
        { value: "bank_panin_syr", label: "PANIN DUBAI SYARIAH" },
        { value: "bank_permata_syr", label: "PERMATA SYARIAH" },
        { value: "bank_qnb_kesawan", label: "QNB INDONESIA" },
        { value: "bank_rabobank", label: "RABOBANK INTERNATIONAL INDONESIA" },
        { value: "bank_sakuku", label: "SAKUKU" },
        { value: "bank_saldo_flip", label: "SALDO FLIP" },
        { value: "bank_sbi_indonesia", label: "SBI INDONESIA" },
        { value: "bank_kesejahteraan_ekonomi", label: "SEABANK/BANK BKE" },
        { value: "bank_standard_chartered", label: "STANDARD CHARTERED BANK" },
        { value: "bank_super", label: "SUPERBANK" },
        { value: "bank_uob", label: "TMRW/UOB" },
        { value: "bank_tokopedia", label: "TOKOPEDIA" },
        { value: "bank_bukopin", label: "WOKEE/BUKOPIN" },
        { value: "bank_krom", label: "KROM BANK INDONESIA" },
        { value: "bank_deutsche", label: "DEUTSCHE BANK AG" },
        { value: "bank_saqu", label: "BANK SAQU" },
    ],
    ewallets: [
        { value: "wallet_dana", label: "DANA" },
        { value: "wallet_ovo", label: "OVO" },
        { value: "gopay_user", label: "GOPAY USER" },
        { value: "gopay_driver", label: "GOPAY DRIVER" },
        { value: "wallet_shopeepay", label: "SHOPEEPAY" },
        { value: "wallet_linkaja", label: "LINK AJA" },
        { value: "grab_user", label: "GRAB USER" },
        { value: "wallet_isaku", label: "I.SAKU" },
    ],
}
